---
- name: Add ES package key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    keyring: /etc/apt/trusted.gpg.d/elasticsearch-keyring.gpg

- name: Add ES repository
  apt_repository:
    repo: deb [signed-by=/etc/apt/trusted.gpg.d/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main
    state: present
    filename: elasticsearch

- name: Elasticsearch install packages
  apt:
    name: "{{ elasticsearch__default_packages }}"
    update_cache: yes
    state: present
  when: elasticsearch__install

- name: Setup ES config file
  template:
    src: elasticsearch.yml
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: "0660"
  when: elasticsearch__configure
  # notify: Restart ES

- name: Enable ES service
  service:
    name: elasticsearch
    enabled: yes
  when:
    - elasticsearch__configure

- name: Start ES service
  service:
    name: elasticsearch
    state: started
  register: service_started
  when:
    - elasticsearch__configure
